name: islamic_will
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  fluttertoast: ^8.2.10
  hooks_riverpod: ^2.6.1
  http_interceptor: ^2.0.0
  intl: ^0.20.2
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  syncfusion_flutter_charts: ^28.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
