name: islamic_will
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  easy_stepper: ^0.8.5+1
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.1+1
  flutter_hooks: ^0.20.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  get_storage: ^2.1.1
  hooks_riverpod: ^2.6.1
  http_interceptor: ^2.0.0
  iconify: ^0.0.1
  iconify_flutter: ^0.0.7
  intl: ^0.20.2
  persistent_bottom_nav_bar: ^6.2.1
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  syncfusion_flutter_charts: ^28.1.41
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
